---
name: azure_tf_wf
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  terraform:
    runs-on: Windows
    steps:
    - name: gitcheckout
      uses: actions/checkout@v3
    - name: setup-terraform
      uses: hashicorp/setup-terraform@v2
    - name: run-terraform
      working-directory: ./hub/compute/virtualmachines
    - name: terraform-init
      run: terraform init
    - name: terraform-apply
      run: terraform apply -auto-approve
